# See the documentation for more information:
# https://packit.dev/docs/configuration/
actions:
    changelog-entry:
        - bash -c 'echo "- New upstream release"'
    post-upstream-clone:
        - wget https://src.fedoraproject.org/rpms/rust-zincati/raw/rawhide/f/rust-zincati.spec

specfile_path: rust-zincati.spec
downstream_package_name: rust-zincati
upstream_package_name: zincati
upstream_tag_template: v{version}
# add or remove files that should be synced
files_to_sync:
    - rust-zincati.spec
    - .packit.yaml

jobs:

- job: propose_downstream
  trigger: release
  # https://packit.dev/docs/configuration#aliases
  dist_git_branches:
    - fedora-development
    - fedora-latest-stable

- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-development
    - fedora-latest-stable

- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-development
    - fedora-latest-stable
