[package]
name = "zincati"
version = "0.0.2"
description = "Update agent for Fedora CoreOS"
license = "Apache-2.0"
keywords = ["cincinnati", "coreos", "fedora", "rpm-ostree"]
authors = ["Luca Bruno <luca.bruno@coreos.com>"]
repository = "https://github.com/coreos/zincati"
edition = "2018"

[dependencies]
actix = "^0.8.1"
cfg-if = "^0.1.9"
env_logger = "^0.6.1"
envsubst = "^0.1.0"
failure = "^0.1.5"
futures = "^0.1.26"
chrono = "^0.4.6"
glob = "^0.3.0"
lazy_static = "^1.3.0"
liboverdrop = "^0.0.1"
libsystemd = "^0.1.0"
log = "^0.4.6"
prometheus = { version = "^0.7.0", default-features = false }
reqwest = "^0.9.13"
serde = { version = "^1.0.93", features = ["derive"] }
serde_json = "^1.0.39"
structopt = "^0.2.15"
tokio = "^0.1.21"
toml = "^0.5.0"
url_serde = "^0.2.0"

[dev-dependencies]
mockito = "^0.17"
proptest = "^0.9"
tokio = "^0.1"

[profile.release]
lto = true

[package.metadata.release]
sign-commit = true
upload-doc = false
disable-publish = true
disable-push = true
pre-release-commit-message = "cargo: zincati release {{version}}"
pro-release-commit-message = "cargo: development version bump"
tag-message = "zincati {{version}}"
