[package]
name = "zincati"
version = "0.0.6-alpha.0"
description = "Update agent for Fedora CoreOS"
license = "Apache-2.0"
keywords = ["cincinnati", "coreos", "fedora", "rpm-ostree"]
authors = ["Luca Bruno <luca.bruno@coreos.com>"]
repository = "https://github.com/coreos/zincati"
edition = "2018"

[dependencies]
actix = "^0.8.1"
cfg-if = "^0.1.9"
env_logger = "^0.6.2"
envsubst = "^0.1.0"
fail = "^0.3.0"
failure = "^0.1.5"
futures = "^0.1.29"
chrono = "^0.4.9"
glob = "^0.3.0"
lazy_static = "^1.4.0"
liboverdrop = "^0.0.2"
libsystemd = "^0.1.0"
log = "^0.4.8"
maplit = "^1.0"
ordered-float = { version = "^1.0.2", features = ["serde"] }
prometheus = { version = "^0.7.0", default-features = false }
rand = "^0.7.2"
reqwest = "^0.9.20"
serde = { version = "^1.0.101", features = ["derive"] }
serde_json = "^1.0.40"
structopt = "^0.3.2"
tokio = "^0.1.22"
toml = "^0.5.3"
url_serde = "^0.2.0"

[dev-dependencies]
mockito = "^0.20"
proptest = "^0.9"
tokio = "^0.1"

[features]
failpoints = [ "fail/failpoints" ]

[profile.release]
lto = true

[package.metadata.release]
sign-commit = true
upload-doc = false
disable-publish = true
disable-push = true
pre-release-commit-message = "cargo: zincati release {{version}}"
pro-release-commit-message = "cargo: development version bump"
tag-message = "zincati {{version}}"
