---
name: Containers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-fcos:
    name: "Build in FCOS buildroot"
    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and test
        run: make
